name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd djangoproject
          python manage.py test

      - name: SSH commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: 134.209.228.130
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/djangoproject/djangoproject
            source /root/venv/bin/activate
            git pull origin master
            python manage.py migrate
            python manage.py collectstatic --noinput
            supervisorctl restart all
